apiVersion: apps/v1
kind: Deployment
metadata:
  name: recaudaciones-api
  namespace: recaudaciones
spec:
  replicas: 3
  selector:
    matchLabels:
      app: recaudaciones-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: recaudaciones-api
    spec:
      containers:
        - name: recaudaciones-api
          image: gio0603/reca-api:d4e79f2
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: neon-db
                  key: DATABASE_URL
            # Collector
            # ==== NUEVO (OTel -> Collector) ====
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: "coralogix-opentelemetry-collector.observability.svc:4317"
            # identidad del servicio (APM)
            - name: OTEL_SERVICE_NAME
              value: "core-banco-api"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "cx.application.name=core-banco,cx.subsystem.name=api,service.namespace=recaudaciones,service.version=13c4bfc"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /readyz
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /livez
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold:
          startupProbe:
            httpGet:
              path: /healthz
              port: 3000
            periodSeconds: 5
            failureThreshold: 30
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
